/// Turns a `MachineDesc` into Swift source.
///
/// The shape is fixed by `Sources/TabularCenterCheck/ReferenceTimer.swift`, which is
/// hand-written and kept building forever. This emitter has to reproduce it,
/// generated code is never committed, and `tools/verify swift-codegen`
/// compiles that output against `codegen-support/` -- a golden alone proves
/// only determinism, not that the output is Swift.
///
/// ## Where things live
///
/// Every type the description names belongs to the machine's enum, as in
/// ARCHITECTURE 11.3 (`enum Timer { enum S ...; enum A ... }`): `Timer.S`,
/// `Timer.Ctx`, and the narrowed `Timer.Running`. Everything generated goes
/// into `extension Timer` -- `step`, `perform`, `TABLE`, `PAYLOADS` -- except
/// the cell protocol, which a child's parent must be able to inherit.
///
/// That is what lets two machines share a module: at file scope, both would
/// declare `step` and `TABLE`. And it is what a child is reached through: a
/// `DELEGATE` to `.retry` calls `Retry.step`, and the parent's protocol
/// refines `RetryCells`.
public func emit(_ d: MachineDesc) -> String {
    let color = Color(d.prototypeModifiers)
    let own = { (name: String) in "\(d.machine).\(name)" }
    let stepType = "Step<\(own(d.stateType)), \(own(d.effectType))>"
    var out = ""

    out += "// Generated by tabular-center. Do not edit.\n"
    out += "//\n"
    out += "// The dispatcher exists ONLY here. A developer never writes a `switch`, so\n"
    out += "// `default:` is not a temptation -- it is not available. That is the\n"
    out += "// difference between a convention and a guarantee.\n"
    out += "import TabularCenter\n\n"

    for line in refusals(d) {
        out += "#error(\(q(line)))\n"
    }

    out += "/// The cell surface: one required member per non-static cell, with narrowed\n"
    out += "/// argument types.\n"
    out += "///\n"
    out += "/// A protocol, not a base class, because this is what composes: a class\n"
    out += "/// extends one parent, so a base class would cap composition at a single\n"
    out += "/// child. Protocols are Swift's trait bounds.\n"
    let supers = d.children.map { "\(childType($0))Cells" }
    out += "protocol \(d.machine)Cells"
    out += supers.isEmpty ? " {\n" : ": \(supers.joined(separator: ", ")) {\n"

    for (i, row) in d.rows.enumerated() {
        for (j, c) in row.enumerated() {
            switch c {
            case .handle:
                out += "    \(color.prefix)func \(member(d, i, j))(_ ctx: \(own(d.ctxType))"
                out += argList(d, i, j)
                out += ")\(color.suffix) -> \(stepType)\n"
            case let .delegate(child):
                guard let ch = d.children.first(where: { $0.alias == child }) else { continue }
                out += "    \(color.prefix)func \(member(d, i, j))ToChild(_ ctx: \(own(d.ctxType))"
                out += argList(d, i, j)
                out += ")\(color.suffix) -> \(childType(ch)).\(ch.actionType)?\n"
            default:
                break
            }
        }
    }

    for ch in d.children {
        let c = childType(ch)
        out += "\n    // Lens onto `\(c)`. Per child, not per cell.\n"
        out += "    func \(ch.alias)ChildState(_ s: \(own(d.stateType))) -> \(c).\(ch.stateType)\n"
        out += "    func \(ch.alias)Embed(_ s: \(own(d.stateType)), _ child: \(c).\(ch.stateType)) -> \(own(d.stateType))\n"
        out += "    func \(ch.alias)Lift(_ effect: \(c).\(ch.effectType)) -> \(own(d.effectType))\n"
        out += "    func \(ch.alias)ChildCtx(_ ctx: \(own(d.ctxType))) -> \(c).\(ch.ctxType)\n"
    }

    if !d.effects.isEmpty {
        out += "\n    // One required member per effect variant. Add an effect and every\n"
        out += "    // handler stops compiling.\n"
        for e in d.effects {
            out += "    \(color.prefix)func \(lower(e.name))(_ ctx: \(own(d.ctxType))"
            out += effectParam(e)
            out += ")\(color.suffix) -> \(own(d.actionType))?\n"
        }
    }
    out += "}\n\n"

    if let r = d.render {
        let rc = Color(r.modifiers)
        out += "/// The rendering surface: one required member per state, the state narrowed.\n"
        out += "///\n"
        out += "/// Its own prototype and its own color, independent of the cells'. Add a\n"
        out += "/// state and every renderer stops compiling, as every handler does when a\n"
        out += "/// cell appears.\n"
        out += "protocol \(d.machine)Renders {\n"
        for st in d.states {
            let arg = st.hasPayload ? "_ state: \(own(st.name))" : ""
            if let bld = r.builder {
                out += "    associatedtype \(cap(st.name))Body: \(r.conformance)\n"
                out += "    \(rc.prefix)@\(bld) func render\(cap(st.name))(\(arg))\(rc.suffix) -> \(cap(st.name))Body\n"
            } else {
                out += "    \(rc.prefix)func render\(cap(st.name))(\(arg))\(rc.suffix) -> \(r.returnType)\n"
            }
        }
        out += "}\n\n"
    }

    out += "extension \(d.machine) {\n"

    out += "    /// Dispatch one `(state, action)` pair. No `default:` branch.\n"
    out += "    \(color.prefix)static func step(_ cells: \(d.machine)Cells, _ ctx: \(own(d.ctxType)), "
    out += "_ s: \(own(d.stateType)), _ a: \(own(d.actionType)))\(color.suffix) -> \(stepType) {\n"
    out += "        switch (s, a) {\n"
    for (i, row) in d.rows.enumerated() {
        for (j, c) in row.enumerated() {
            switch c {
            case .handle, .delegate:
                let sb = bind(d.states[i], side: "s", avoid: reserved, owner: d.machine)
                let ab = bind(d.actions[j], side: "a", avoid: reserved.union(sb.names), owner: d.machine)
                let binds = !sb.names.isEmpty || !ab.names.isEmpty
                var args = "ctx"
                if d.states[i].hasPayload { args += ", \(sb.value)" }
                if d.actions[j].hasPayload { args += ", \(ab.value)" }
                out += "        case \(binds ? "let " : "")(\(sb.pattern), \(ab.pattern)):\n"
                if case let .delegate(child) = c {
                    out += "            let childAction = \(color.call)cells.\(member(d, i, j))ToChild(\(args))\n"
                    out += "            return \(color.call)delegateTo\(cap(child))(cells, ctx, s, childAction)\n"
                } else {
                    out += "            return \(color.call)cells.\(member(d, i, j))(\(args))\n"
                }
            default:
                out += "        case (.\(lower(d.states[i].name)), .\(lower(d.actions[j].name))):\n"
                out += "            return \(arm(d, i, j))\n"
            }
        }
    }
    out += "        }\n    }\n"

    for ch in d.children {
        let c = childType(ch)
        out += "\n    /// Run `\(c)` and fold the result back through the lens.\n"
        out += "    ///\n"
        out += "    /// A nil child action reports **ignored**, not stay: a parent action the\n"
        out += "    /// child's alphabet does not contain was not handled.\n"
        out += "    \(color.prefix)private static func delegateTo\(cap(ch.alias))(\n"
        out += "        _ cells: \(d.machine)Cells, _ ctx: \(own(d.ctxType)), _ s: \(own(d.stateType)), "
        out += "_ childAction: \(c).\(ch.actionType)?\n"
        out += "    )\(color.suffix) -> \(stepType) {\n"
        out += "        guard let childAction else { return .ignored }\n"
        out += "        let childStep = \(color.call)\(c).step(\n"
        out += "            cells, cells.\(ch.alias)ChildCtx(ctx), cells.\(ch.alias)ChildState(s), childAction)\n"
        out += "        let effects = childStep.effects.map { cells.\(ch.alias)Lift($0) }\n"
        out += "        switch childStep {\n"
        out += "        case let .go(next, _): return .go(cells.\(ch.alias)Embed(s, next), effects: effects)\n"
        out += "        case .stay: return .stay(effects: effects)\n"
        out += "        case .ignored: return .ignored\n"
        out += "        }\n"
        out += "    }\n"
    }

    if !d.effects.isEmpty {
        out += "\n    /// Carry out one effect, returning any follow-up action.\n"
        out += "    \(color.prefix)static func perform(_ cells: \(d.machine)Cells, _ ctx: \(own(d.ctxType)), "
        out += "_ f: \(own(d.effectType)))\(color.suffix) -> \(own(d.actionType))? {\n"
        out += "        switch f {\n"
        for e in d.effects {
            let b = bind(e, side: "e", avoid: ["cells", "ctx", "f"], owner: d.machine)
            if b.names.isEmpty {
                out += "        case .\(lower(e.name)):\n"
                out += "            return \(color.call)cells.\(lower(e.name))(ctx)\n"
            } else {
                let arg = b.names.count == 1
                    ? b.names[0]
                    : "(" + zip(e.fields, b.names).map { f, n in
                        f.name.isEmpty ? n : "\(f.name): \(n)"
                    }.joined(separator: ", ") + ")"
                out += "        case let \(b.pattern):\n"
                out += "            return \(color.call)cells.\(lower(e.name))(ctx, \(arg))\n"
            }
        }
        out += "        }\n    }\n"
    }

    if let r = d.render {
        let rc = Color(r.modifiers)
        out += "\n    /// Render one state. No `default:` branch.\n"
        let lead: String
        if let bld = r.builder {
            out += "    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)\n"
            out += "    \(rc.prefix)@\(bld) static func render<R: \(d.machine)Renders>(_ renders: R, _ s: \(own(d.stateType)))"
            out += "\(rc.suffix) -> some \(r.conformance) {\n"
            lead = ""
        } else {
            out += "    \(rc.prefix)static func render(_ renders: \(d.machine)Renders, _ s: \(own(d.stateType)))"
            out += "\(rc.suffix) -> \(r.returnType) {\n"
            lead = "return "
        }
        out += "        switch s {\n"
        for st in d.states {
            let b = bind(st, side: "s", avoid: ["renders", "s"], owner: d.machine)
            if st.hasPayload && !b.names.isEmpty {
                out += "        case let \(b.pattern):\n"
                out += "            \(lead)\(rc.call)renders.render\(cap(st.name))(\(b.value))\n"
            } else {
                out += "        case .\(lower(st.name)):\n"
                out += "            \(lead)\(rc.call)renders.render\(cap(st.name))()\n"
            }
        }
        out += "        }\n    }\n"
    }

    for h in d.hops { out += hop(d, h, color, own) }

    out += "\n    /// The matrix as inert data. Diagrams, lints, and coverage read this.\n"
    out += "    static let TABLE = Table(\n"
    out += "        machine: \(q(d.machine)),\n"
    out += "        states: [\(d.states.map { q($0.name) }.joined(separator: ", "))],\n"
    out += "        actions: [\(d.actions.map { q($0.name) }.joined(separator: ", "))],\n"
    out += "        cells: [\n"
    for row in d.rows {
        out += "            [\(row.map(cellData).joined(separator: ", "))],\n"
    }
    out += "        ],\n"
    out += "        initial: \(q(d.initial))\n"
    out += "    )\n"

    out += "\n    /// State payload fields, as `(state, field, type)`.\n"
    let entries = d.states.flatMap { v in v.fields.map { (v.name, $0.name, $0.type) } }
    if entries.isEmpty {
        out += "    static let PAYLOADS: Payloads = []\n"
    } else {
        out += "    static let PAYLOADS: Payloads = [\n"
        for e in entries {
            out += "        (state: \(q(e.0)), field: \(q(e.1)), type: \(q(e.2))),\n"
        }
        out += "    ]\n"
    }
    out += "}\n"
    return out
}

/// The prototype's modifiers, split by where Swift wants them.
///
/// `MachineSyntax` records attributes, modifiers and effect specifiers in one
/// list, in source order, and copies them verbatim (ARCHITECTURE 5). Verbatim
/// is right; *one place* is not. `@MainActor` goes before `func`, while `async`
/// and `throws` go after the parameter list -- and every call into a colored
/// member needs `try` / `await`, which is how the color reaches the caller.
private struct Color {
    let prefix: String
    let suffix: String
    let call: String

    init(_ mods: [String]) {
        let specifiers: Set<String> = ["async", "throws", "rethrows"]
        let before = mods.filter { !specifiers.contains($0) }
        let after = mods.filter { specifiers.contains($0) }
        prefix = before.isEmpty ? "" : before.joined(separator: " ") + " "
        suffix = after.isEmpty ? "" : " " + after.joined(separator: " ")
        let throwing = after.contains("throws") || after.contains("rethrows")
        call = (throwing ? "try " : "") + (after.contains("async") ? "await " : "")
    }
}

private let reserved: Set<String> = ["cells", "ctx", "s", "a"]

private func bind(_ v: Variant, side: String, avoid: Set<String>, owner: String)
    -> (pattern: String, value: String, names: [String])
{
    let base = ".\(lower(v.name))"
    let narrowed = "\(owner).\(v.name)"
    guard v.hasPayload, !v.fields.isEmpty else { return (base, "\(narrowed)()", []) }
    var taken = avoid
    var names: [String] = []
    for (k, f) in v.fields.enumerated() {
        var n = f.name.isEmpty ? "\(side)\(k)" : f.name
        if taken.contains(n) { n = side + cap(n) }
        taken.insert(n)
        names.append(n)
    }
    let labelled = zip(v.fields, names).map { f, n in f.name.isEmpty ? n : "\(f.name): \(n)" }
    return (
        "\(base)(\(names.joined(separator: ", ")))",
        "\(narrowed)(\(labelled.joined(separator: ", ")))",
        names
    )
}

private func effectParam(_ e: Variant) -> String {
    guard e.hasPayload, !e.fields.isEmpty else { return "" }
    if e.fields.count == 1 { return ", _ effect: \(e.fields[0].type)" }
    let parts = e.fields.map { $0.name.isEmpty ? $0.type : "\($0.name): \($0.type)" }
    return ", _ effect: (\(parts.joined(separator: ", ")))"
}

private func refusals(_ d: MachineDesc) -> [String] {
    var out: [String] = []
    for v in d.states + d.actions + d.effects where v.hasPayload && v.fields.isEmpty {
        out.append("tabular-center: the payload fields of `\(v.name)` are unknown, so the generator cannot bind them")
    }
    for h in d.hops {
        let v = d.states[h.from]
        if v.hasPayload && v.fields.contains(where: { $0.name.isEmpty }) {
            out.append("tabular-center: the hop from `\(v.name)` needs its payload fields named, to rebuild the state from its narrowed struct")
        }
    }
    if let r = d.render, r.builder != nil {
        if r.conformance.isEmpty {
            out.append("tabular-center: a result-builder rendering prototype needs the protocol its views conform to, such as `View`")
        }
        if !Color(r.modifiers).suffix.isEmpty {
            out.append("tabular-center: a result-builder rendering prototype cannot be `async` or `throws`; render synchronously and step asynchronously")
        }
    }
    return out
}

public func hopOutcomes(_ d: MachineDesc, _ h: HopDesc) -> [Int] {
    var out: Set<Int> = [h.to]
    for cell in d.rows[h.from] {
        switch cell {
        case let .go(target, _, _):
            if let i = d.states.firstIndex(where: { $0.name == target }) { out.insert(i) }
        case .emit, .ignore, .delegate:
            out.insert(h.from)
        case .handle:
            out.formUnion(d.states.indices)
        case .unreachable:
            break
        }
    }
    return out.sorted()
}

private func hop(
    _ d: MachineDesc, _ h: HopDesc, _ color: Color, _ own: (String) -> String
) -> String {
    let name = member(d, h.from, h.action)
    let type = cap(name)
    let from = d.states[h.from]
    let to = d.states[h.to]
    let outcomes = hopOutcomes(d, h)
    let others = outcomes.filter { $0 != h.to }
    let fx = "[\(own(d.effectType))]"
    func carried(_ v: Variant) -> String { v.hasPayload ? "(\(own(v.name)), \(fx))" : fx }

    var out = "\n    /// Where `\(from.name)` can go when an action arrives, on the path through\n"
    out += "    /// `\(from.name) -\(d.actions[h.action].name)-> \(to.name)`: `\(to.name)` is the happy outcome, the rest\n"
    out += "    /// are what else the `\(from.name)` row can produce. Each carries the step's effects.\n"
    out += "    enum \(type) {\n"
    for i in outcomes {
        let v = d.states[i]
        out += v.hasPayload
            ? "        case \(lower(v.name))(\(own(v.name)), effects: \(fx))\n"
            : "        case \(lower(v.name))(effects: \(fx))\n"
    }
    out += "\n        /// The happy outcome, or each handler's answer for the others. A handler\n"
    out += "        /// leaves by throwing, which `rethrows` passes on.\n"
    let params = others.map { i -> String in
        let v = d.states[i]
        let args = v.hasPayload ? "\(own(v.name)), \(fx)" : fx
        return "\(lower(v.name)): (\(args)) throws -> \(carried(to))"
    }
    let rethrowsClause = others.isEmpty ? "" : " rethrows"
    out += "        func elvis(\(params.joined(separator: ", ")))\(rethrowsClause) -> \(carried(to)) {\n"
    out += "            switch self {\n"
    for i in outcomes {
        let v = d.states[i]
        let c = lower(v.name)
        let bound = v.hasPayload ? "(state, effects)" : "(effects)"
        let args = v.hasPayload ? "state, effects" : "effects"
        if i == h.to {
            out += "            case let .\(c)\(bound): return \(v.hasPayload ? "(state, effects)" : "effects")\n"
        } else {
            out += "            case let .\(c)\(bound): return try \(c)(\(args))\n"
        }
    }
    out += "            }\n        }\n    }\n"

    let stateParam = from.hasPayload ? "_ state: \(own(from.name)), " : ""
    let rebuilt = from.hasPayload
        ? ".\(lower(from.name))(" + from.fields.map { "\($0.name): state.\($0.name)" }.joined(separator: ", ") + ")"
        : ".\(lower(from.name))"
    out += "\n    /// `\(from.name)` receives `action`; the matrix decides the outcome. Effects come\n"
    out += "    /// back, never run.\n"
    out += "    \(color.prefix)static func \(name)(_ cells: \(d.machine)Cells, _ ctx: \(own(d.ctxType)), "
    out += "\(stateParam)_ action: \(own(d.actionType)))\(color.suffix) -> \(type) {\n"
    out += "        let current: \(own(d.stateType)) = \(rebuilt)\n"
    out += "        let next: \(own(d.stateType))\n"
    out += "        let effects: \(fx)\n"
    out += "        switch \(color.call)step(cells, ctx, current, action) {\n"
    out += "        case let .go(state, stepEffects): next = state; effects = stepEffects\n"
    out += "        case let .stay(stepEffects): next = current; effects = stepEffects\n"
    out += "        case .ignored: next = current; effects = []\n"
    out += "        }\n"
    out += "        switch next {\n"
    for (i, v) in d.states.enumerated() {
        if outcomes.contains(i) {
            let b = bind(v, side: "s", avoid: ["cells", "ctx", "action", "current", "next", "effects", "state"], owner: d.machine)
            if v.hasPayload && !b.names.isEmpty {
                out += "        case let \(b.pattern): return .\(lower(v.name))(\(b.value), effects: effects)\n"
            } else {
                out += "        case .\(lower(v.name)): return .\(lower(v.name))(effects: effects)\n"
            }
        } else {
            out += "        case .\(lower(v.name)): fatalError(\"tabular-center: the `\(from.name)` row cannot produce `\(v.name)`\")\n"
        }
    }
    out += "        }\n    }\n"
    return out
}

/// One member of the generated `Cells` protocol, and what it was generated
/// from -- for `tabular-center::member-collision`.
struct GeneratedMember {
    let name: String
    let origin: String
}

func cellsMembers(_ d: MachineDesc) -> [GeneratedMember] {
    var out: [GeneratedMember] = []
    for (i, row) in d.rows.enumerated() {
        for (j, cell) in row.enumerated() {
            let at = "cell (\(d.states[i].name), \(d.actions[j].name))"
            switch cell {
            case .handle:
                out.append(GeneratedMember(name: member(d, i, j), origin: at))
            case .delegate:
                out.append(GeneratedMember(name: member(d, i, j) + "ToChild", origin: at))
            default:
                break
            }
        }
    }
    for ch in d.children {
        for suffix in ["ChildState", "Embed", "Lift", "ChildCtx"] {
            out.append(GeneratedMember(name: ch.alias + suffix, origin: "child `\(ch.alias)`"))
        }
    }
    for e in d.effects {
        out.append(GeneratedMember(name: lower(e.name), origin: "effect \(e.name)"))
    }
    for h in d.hops {
        let at = "hop (\(d.states[h.from].name), \(d.actions[h.action].name))"
        out.append(GeneratedMember(name: member(d, h.from, h.action), origin: at))
    }
    return out
}

private func member(_ d: MachineDesc, _ i: Int, _ j: Int) -> String {
    lower(d.states[i].name) + cap(d.actions[j].name)
}

private func argList(_ d: MachineDesc, _ i: Int, _ j: Int) -> String {
    var s = ""
    if d.states[i].hasPayload { s += ", _ state: \(d.machine).\(d.states[i].name)" }
    if d.actions[j].hasPayload { s += ", _ action: \(d.machine).\(d.actions[j].name)" }
    return s
}

private func arm(_ d: MachineDesc, _ i: Int, _ j: Int) -> String {
    switch d.rows[i][j] {
    case .ignore, .handle, .delegate:
        return ".ignored"
    case .unreachable:
        return "fatalError(\(q("tabular-center: \(d.states[i].name) x \(d.actions[j].name) was declared UNREACHABLE but occurred")))"
    case let .go(target, args, effects):
        let e = effects.map { ".\(lower($0))" }.joined(separator: ", ")
        return ".go(.\(lower(target))\(args), effects: [\(e)])"
    case let .emit(effects):
        let e = effects.map { ".\(lower($0))" }.joined(separator: ", ")
        return ".stay(effects: [\(e)])"
    }
}

private func cellData(_ c: CellDesc) -> String {
    switch c {
    case .ignore: return ".ignore"
    case .handle: return ".handle"
    case .unreachable: return ".unreachable"
    case let .go(target, _, effects):
        let e = effects.map { q(effectName($0)) }.joined(separator: ", ")
        return ".go(target: \(q(target)), effects: [\(e)])"
    case let .emit(effects):
        let e = effects.map { q(effectName($0)) }.joined(separator: ", ")
        return ".emit(effects: [\(e)])"
    case let .delegate(child):
        return ".delegate(child: \(q(child)))"
    }
}

private func childType(_ ch: ChildDesc) -> String { cap(ch.alias) }

private func q(_ s: String) -> String { "\"\(s)\"" }
private func lower(_ s: String) -> String { s.isEmpty ? s : s.prefix(1).lowercased() + s.dropFirst() }
private func cap(_ s: String) -> String { s.isEmpty ? s : s.prefix(1).uppercased() + s.dropFirst() }
