/// Turns a `MachineDesc` into Swift source.
///
/// The shape is fixed by `Sources/TabulaCheck/ReferenceTimer.swift`, which is
/// hand-written and kept building forever. This emitter has to reproduce it,
/// generated code is never committed, and `tools/verify swift-codegen`
/// compiles that output against `codegen-support/` -- a golden alone proves
/// only determinism, not that the output is Swift.
///
/// ## Where things live
///
/// Every type the description names belongs to the machine's enum, as in
/// ARCHITECTURE 11.3 (`enum Timer { enum S ...; enum A ... }`): `Timer.S`,
/// `Timer.Ctx`, and the narrowed `Timer.Running`. Everything generated goes
/// into `extension Timer` -- `step`, `perform`, `TABLE`, `PAYLOADS` -- except
/// the cell protocol, which a child's parent must be able to inherit.
///
/// That is what lets two machines share a module: at file scope, both would
/// declare `step` and `TABLE`. And it is what a child is reached through: a
/// `DELEGATE` to `.retry` calls `Retry.step`, and the parent's protocol
/// refines `RetryCells`.
public func emit(_ d: MachineDesc) -> String {
    let color = Color(d.prototypeModifiers)
    let own = { (name: String) in "\(d.machine).\(name)" }
    let stepType = "Step<\(own(d.stateType)), \(own(d.effectType))>"
    var out = ""

    out += "// Generated by tabula. Do not edit.\n"
    out += "//\n"
    out += "// The dispatcher exists ONLY here. A developer never writes a `switch`, so\n"
    out += "// `default:` is not a temptation -- it is not available. That is the\n"
    out += "// difference between a convention and a guarantee.\n"
    out += "import Tabula\n\n"

    // -- refusals ------------------------------------------------------
    //
    // What this emitter cannot produce correctly, it refuses at the top of the
    // file, in the user's build, naming the variant. The alternative is source
    // that fails to compile somewhere in the middle, with a message about
    // generated code the user never wrote.
    for line in refusals(d) {
        out += "#error(\(q(line)))\n"
    }

    // -- cell surface --------------------------------------------------
    out += "/// The cell surface: one required member per non-static cell, with narrowed\n"
    out += "/// argument types.\n"
    out += "///\n"
    out += "/// A protocol, not a base class, because this is what composes: a class\n"
    out += "/// extends one parent, so a base class would cap composition at a single\n"
    out += "/// child. Protocols are Swift's trait bounds.\n"
    let supers = d.children.map { "\(childType($0))Cells" }
    out += "protocol \(d.machine)Cells"
    out += supers.isEmpty ? " {\n" : ": \(supers.joined(separator: ", ")) {\n"

    for (i, row) in d.rows.enumerated() {
        for (j, c) in row.enumerated() {
            switch c {
            case .handle:
                out += "    \(color.prefix)func \(member(d, i, j))(_ ctx: \(own(d.ctxType))"
                out += argList(d, i, j)
                out += ")\(color.suffix) -> \(stepType)\n"
            case let .delegate(child):
                // The action prism, and the only per-cell part of composition.
                // Narrowed like a HANDLE cell, as `Compose.swift`'s
                // `retryingRunToChild(_ ctx: JobCtx, _ s: JobRetrying)`.
                guard let ch = d.children.first(where: { $0.alias == child }) else { continue }
                out += "    \(color.prefix)func \(member(d, i, j))ToChild(_ ctx: \(own(d.ctxType))"
                out += argList(d, i, j)
                out += ")\(color.suffix) -> \(childType(ch)).\(ch.actionType)?\n"
            default:
                break
            }
        }
    }

    // Lens members are per CHILD, not per cell: a second delegate cell to the
    // same child reuses them. Only the action prism above is per cell.
    //
    // The lens takes the parent's whole state, as Kotlin's does: one lens
    // serves every DELEGATE cell to the child, and those cells may sit in
    // states with different payloads. Uncolored, as in Kotlin -- it is a
    // projection, not a cell.
    for ch in d.children {
        let c = childType(ch)
        out += "\n    // Lens onto `\(c)`. Per child, not per cell.\n"
        out += "    func \(ch.alias)ChildState(_ s: \(own(d.stateType))) -> \(c).\(ch.stateType)\n"
        out += "    func \(ch.alias)Embed(_ s: \(own(d.stateType)), _ child: \(c).\(ch.stateType)) -> \(own(d.stateType))\n"
        out += "    func \(ch.alias)Lift(_ effect: \(c).\(ch.effectType)) -> \(own(d.effectType))\n"
        out += "    func \(ch.alias)ChildCtx(_ ctx: \(own(d.ctxType))) -> \(c).\(ch.ctxType)\n"
    }

    if !d.effects.isEmpty {
        out += "\n    // One required member per effect variant. Add an effect and every\n"
        out += "    // handler stops compiling.\n"
        for e in d.effects {
            out += "    \(color.prefix)func \(lower(e.name))(_ ctx: \(own(d.ctxType))"
            out += effectParam(e)
            out += ")\(color.suffix) -> \(own(d.actionType))?\n"
        }
    }
    out += "}\n\n"

    // -- generated members, in the machine's namespace -------------------
    out += "extension \(d.machine) {\n"

    // -- dispatcher ----------------------------------------------------
    //
    // Only HANDLE and DELEGATE arms bind payloads, because only they hand the
    // payload on. Every other arm matches the bare case, which Swift allows
    // for a case with associated values -- and which leaves no unused
    // bindings behind.
    out += "    /// Dispatch one `(state, action)` pair. No `default:` branch.\n"
    out += "    \(color.prefix)static func step(_ cells: \(d.machine)Cells, _ ctx: \(own(d.ctxType)), "
    out += "_ s: \(own(d.stateType)), _ a: \(own(d.actionType)))\(color.suffix) -> \(stepType) {\n"
    out += "        switch (s, a) {\n"
    for (i, row) in d.rows.enumerated() {
        for (j, c) in row.enumerated() {
            switch c {
            case .handle, .delegate:
                let sb = bind(d.states[i], side: "s", avoid: reserved, owner: d.machine)
                let ab = bind(d.actions[j], side: "a", avoid: reserved.union(sb.names), owner: d.machine)
                let binds = !sb.names.isEmpty || !ab.names.isEmpty
                var args = "ctx"
                if d.states[i].hasPayload { args += ", \(sb.value)" }
                if d.actions[j].hasPayload { args += ", \(ab.value)" }
                out += "        case \(binds ? "let " : "")(\(sb.pattern), \(ab.pattern)):\n"
                if case let .delegate(child) = c {
                    // Two statements rather than a nested call, so a colored
                    // machine writes `try await` once per call, not twice in
                    // one expression.
                    out += "            let childAction = \(color.call)cells.\(member(d, i, j))ToChild(\(args))\n"
                    out += "            return \(color.call)delegateTo\(cap(child))(cells, ctx, s, childAction)\n"
                } else {
                    out += "            return \(color.call)cells.\(member(d, i, j))(\(args))\n"
                }
            default:
                out += "        case (.\(lower(d.states[i].name)), .\(lower(d.actions[j].name))):\n"
                out += "            return \(arm(d, i, j))\n"
            }
        }
    }
    out += "        }\n    }\n"

    // -- delegation ------------------------------------------------------
    //
    // One helper per child, as `Compose.swift` and Kotlin's generator write
    // it. It carries the PARENT's color and calls the child's `step` with the
    // parent's `try` / `await`. That is one-way color flow by construction:
    // a colored child under an uncolored parent is a call to an `async` or
    // `throws` function with neither, which swiftc refuses; the reverse is a
    // redundant `await`, which it accepts.
    for ch in d.children {
        let c = childType(ch)
        out += "\n    /// Run `\(c)` and fold the result back through the lens.\n"
        out += "    ///\n"
        out += "    /// A nil child action reports **ignored**, not stay: a parent action the\n"
        out += "    /// child's alphabet does not contain was not handled.\n"
        out += "    \(color.prefix)private static func delegateTo\(cap(ch.alias))(\n"
        out += "        _ cells: \(d.machine)Cells, _ ctx: \(own(d.ctxType)), _ s: \(own(d.stateType)), "
        out += "_ childAction: \(c).\(ch.actionType)?\n"
        out += "    )\(color.suffix) -> \(stepType) {\n"
        out += "        guard let childAction else { return .ignored }\n"
        out += "        let childStep = \(color.call)\(c).step(\n"
        out += "            cells, cells.\(ch.alias)ChildCtx(ctx), cells.\(ch.alias)ChildState(s), childAction)\n"
        out += "        let effects = childStep.effects.map { cells.\(ch.alias)Lift($0) }\n"
        out += "        switch childStep {\n"
        out += "        case let .go(next, _): return .go(cells.\(ch.alias)Embed(s, next), effects: effects)\n"
        out += "        case .stay: return .stay(effects: effects)\n"
        out += "        case .ignored: return .ignored\n"
        out += "        }\n"
        out += "    }\n"
    }

    // -- effect dispatch -----------------------------------------------
    if !d.effects.isEmpty {
        out += "\n    /// Carry out one effect, returning any follow-up action.\n"
        out += "    \(color.prefix)static func perform(_ cells: \(d.machine)Cells, _ ctx: \(own(d.ctxType)), "
        out += "_ f: \(own(d.effectType)))\(color.suffix) -> \(own(d.actionType))? {\n"
        out += "        switch f {\n"
        for e in d.effects {
            let b = bind(e, side: "e", avoid: ["cells", "ctx", "f"], owner: d.machine)
            if b.names.isEmpty {
                out += "        case .\(lower(e.name)):\n"
                out += "            return \(color.call)cells.\(lower(e.name))(ctx)\n"
            } else {
                // One field passes its value, as `ReferenceTimer` passes a
                // `Reason`; several pass a labelled tuple.
                let arg = b.names.count == 1
                    ? b.names[0]
                    : "(" + zip(e.fields, b.names).map { f, n in
                        f.name.isEmpty ? n : "\(f.name): \(n)"
                    }.joined(separator: ", ") + ")"
                out += "        case let \(b.pattern):\n"
                out += "            return \(color.call)cells.\(lower(e.name))(ctx, \(arg))\n"
            }
        }
        out += "        }\n    }\n"
    }

    // -- table ----------------------------------------------------------
    out += "\n    /// The matrix as inert data. Diagrams, lints, and coverage read this.\n"
    out += "    static let TABLE = Table(\n"
    out += "        machine: \(q(d.machine)),\n"
    out += "        states: [\(d.states.map { q($0.name) }.joined(separator: ", "))],\n"
    out += "        actions: [\(d.actions.map { q($0.name) }.joined(separator: ", "))],\n"
    out += "        cells: [\n"
    for row in d.rows {
        out += "            [\(row.map(cellData).joined(separator: ", "))],\n"
    }
    out += "        ],\n"
    out += "        initial: \(q(d.initial))\n"
    out += "    )\n"

    // -- payloads --------------------------------------------------------
    out += "\n    /// State payload fields, as `(state, field, type)`.\n"
    let entries = d.states.flatMap { v in v.fields.map { (v.name, $0.name, $0.type) } }
    if entries.isEmpty {
        out += "    static let PAYLOADS: Payloads = []\n"
    } else {
        out += "    static let PAYLOADS: Payloads = [\n"
        for e in entries {
            out += "        (state: \(q(e.0)), field: \(q(e.1)), type: \(q(e.2))),\n"
        }
        out += "    ]\n"
    }
    out += "}\n"
    return out
}

/// The prototype's modifiers, split by where Swift wants them.
///
/// `MachineSyntax` records attributes, modifiers and effect specifiers in one
/// list, in source order, and copies them verbatim (ARCHITECTURE 5). Verbatim
/// is right; *one place* is not. `@MainActor` goes before `func`, while `async`
/// and `throws` go after the parameter list -- and every call into a colored
/// member needs `try` / `await`, which is how the color reaches the caller.
private struct Color {
    /// Attributes and modifiers: `@MainActor `, `nonisolated `.
    let prefix: String
    /// Effect specifiers, after the parameters: ` async throws`.
    let suffix: String
    /// What a call into a member of this color needs: `try await `.
    let call: String

    init(_ mods: [String]) {
        let specifiers: Set<String> = ["async", "throws", "rethrows"]
        let before = mods.filter { !specifiers.contains($0) }
        let after = mods.filter { specifiers.contains($0) }
        prefix = before.isEmpty ? "" : before.joined(separator: " ") + " "
        suffix = after.isEmpty ? "" : " " + after.joined(separator: " ")
        let throwing = after.contains("throws") || after.contains("rethrows")
        call = (throwing ? "try " : "") + (after.contains("async") ? "await " : "")
    }
}

/// The dispatcher's own parameter names. A payload field bound under one of
/// these would shadow it, and `cells.idleStart(ctx, ...)` would quietly pass
/// the field instead of the context.
private let reserved: Set<String> = ["cells", "ctx", "s", "a"]

/// A pattern binding a variant's payload, and the narrowed value built from it.
///
/// `Running(since: Int)` binds as `.running(since)` and constructs
/// `Timer.Running(since: since)` -- the narrowed struct, declared in the
/// machine's enum beside `S`. An unlabelled field binds positionally
/// (`s0`, `a0`) and constructs without a label.
private func bind(_ v: Variant, side: String, avoid: Set<String>, owner: String)
    -> (pattern: String, value: String, names: [String])
{
    let base = ".\(lower(v.name))"
    let narrowed = "\(owner).\(v.name)"
    guard v.hasPayload, !v.fields.isEmpty else { return (base, "\(narrowed)()", []) }
    var taken = avoid
    var names: [String] = []
    for (k, f) in v.fields.enumerated() {
        var n = f.name.isEmpty ? "\(side)\(k)" : f.name
        if taken.contains(n) { n = side + cap(n) }
        taken.insert(n)
        names.append(n)
    }
    let labelled = zip(v.fields, names).map { f, n in f.name.isEmpty ? n : "\(f.name): \(n)" }
    return (
        "\(base)(\(names.joined(separator: ", ")))",
        "\(narrowed)(\(labelled.joined(separator: ", ")))",
        names
    )
}

/// The effect handler's payload parameter: the value for one field, a
/// labelled tuple for several, nothing for none.
private func effectParam(_ e: Variant) -> String {
    guard e.hasPayload, !e.fields.isEmpty else { return "" }
    if e.fields.count == 1 { return ", _ effect: \(e.fields[0].type)" }
    let parts = e.fields.map { $0.name.isEmpty ? $0.type : "\($0.name): \($0.type)" }
    return ", _ effect: (\(parts.joined(separator: ", ")))"
}

/// Everything this emitter knows it cannot produce, as `#error` messages.
private func refusals(_ d: MachineDesc) -> [String] {
    var out: [String] = []
    // `Variant.fields` may be empty with `hasPayload` true: a generator that
    // cannot resolve a type still gets its lints. It cannot get a binding.
    for v in d.states + d.actions + d.effects where v.hasPayload && v.fields.isEmpty {
        out.append("tabula: the payload fields of `\(v.name)` are unknown, so the generator cannot bind them")
    }
    return out
}

/// Cell member name: `Idle` x `Start` becomes `idleStart`.
///
/// Swift macros can build identifiers, so Swift names cells — the same choice
/// Kotlin makes, and the opposite of Rust, where `macro_rules!` cannot.
private func member(_ d: MachineDesc, _ i: Int, _ j: Int) -> String {
    lower(d.states[i].name) + cap(d.actions[j].name)
}

/// Narrowed arguments, only for variants that carry a payload.
private func argList(_ d: MachineDesc, _ i: Int, _ j: Int) -> String {
    var s = ""
    if d.states[i].hasPayload { s += ", _ state: \(d.machine).\(d.states[i].name)" }
    if d.actions[j].hasPayload { s += ", _ action: \(d.machine).\(d.actions[j].name)" }
    return s
}

/// Every arm but HANDLE and DELEGATE, which bind and are written by the
/// dispatcher itself.
private func arm(_ d: MachineDesc, _ i: Int, _ j: Int) -> String {
    switch d.rows[i][j] {
    case .ignore, .handle, .delegate:
        return ".ignored"
    case .unreachable:
        return "fatalError(\(q("tabula: \(d.states[i].name) x \(d.actions[j].name) was declared UNREACHABLE but occurred")))"
    case let .go(target, args, effects):
        // Verbatim, arguments included: `.stopClock(reason: .cancelled)`.
        let e = effects.map { ".\(lower($0))" }.joined(separator: ", ")
        return ".go(.\(lower(target))\(args), effects: [\(e)])"
    case let .emit(effects):
        let e = effects.map { ".\(lower($0))" }.joined(separator: ", ")
        return ".stay(effects: [\(e)])"
    }
}

private func cellData(_ c: CellDesc) -> String {
    switch c {
    case .ignore: return ".ignore"
    case .handle: return ".handle"
    case .unreachable: return ".unreachable"
    // `TABLE` records WHICH effect a cell emits, not with what: the arguments
    // are the dispatcher's, and the conformance goldens compare names.
    case let .go(target, _, effects):
        let e = effects.map { q(effectName($0)) }.joined(separator: ", ")
        return ".go(target: \(q(target)), effects: [\(e)])"
    case let .emit(effects):
        let e = effects.map { q(effectName($0)) }.joined(separator: ", ")
        return ".emit(effects: [\(e)])"
    case let .delegate(child):
        return ".delegate(child: \(q(child)))"
    }
}

/// A child's namespace: `.delegate(.retry)` names the machine `Retry`.
private func childType(_ ch: ChildDesc) -> String { cap(ch.alias) }

private func q(_ s: String) -> String { "\"\(s)\"" }
private func lower(_ s: String) -> String { s.isEmpty ? s : s.prefix(1).lowercased() + s.dropFirst() }
private func cap(_ s: String) -> String { s.isEmpty ? s : s.prefix(1).uppercased() + s.dropFirst() }
